apiVersion: v2
name: helm-cert-manager
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Strimzi

dependencies:
  - name: strimzi-kafka-operator
    version: "0.38.0"
    repository: "https://strimzi.io/charts"
    condition: strimzi-kafka-operator.enabled
