{
 "title": "001-1 - Log Count Summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Log Total Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Event Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Event Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log Summary By Category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Log Category Percentage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log By Category Summary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "field": "mt.@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log Delay Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Log Delay Percentage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_delay_bucket.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ads_delay_bucket:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Delay Summary",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_delay_bucket.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ads_delay_bucket:*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log By Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Log By Channel",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_log_source.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ads_log_source:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log By Channel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ads_log_source.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ads_log_source:*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Logstash Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Logstash Utilization (Syslog)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "mt.pod_name_syslog.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mt.pod_name_syslog:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash Utilization (Syslog)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "mt.pod_name_syslog.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mt.pod_name_syslog:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash Utilization (Loki)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "mt.pod_name_loki.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mt.pod_name_loki:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logstash Utilization (Loki)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "mt.pod_name_loki.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mt.pod_name_loki:*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}