apiVersion: v1
kind: ConfigMap
metadata:
  name: es-child-filter-cm
  annotations:
    checksum/config1: {{ .Files.Get "scripts/es-child.rb" | sha256sum }}
data:
  es-child.rb: |-
{{ .Files.Get "scripts/es-child.rb" |  indent 4 }}
