{{- with .Values.topics.topic2 }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ .cluster }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
{{ toYaml .config | indent 4 }}  
{{- end }}
