apiVersion: v1
kind: ConfigMap
metadata:
  name: geoip-filter-cm
  annotations:
    checksum/config1: {{ .Files.Get "scripts/geoip.rb" | sha256sum }}
data:
  geoip.rb: |-
{{ .Files.Get "scripts/geoip.rb" |  indent 4 }}
