apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-ads-user
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: minio-ads-user       # name of the k8s Secret to be created
  data:
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      key: initial-secret
      property: MINIO_ACCESS_KEY
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: initial-secret
      property: MINIO_SECRET_KEY
