apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.org/client-max-body-size: 20m
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: minio-ads-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-ads-console
                port:
                  name: https-console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-legacy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.org/client-max-body-size: 20m
spec:
  tls:
    - hosts:
      - {{ .Values.domainLegacy }}
      secretName: minio-ads-cert-legacy
  rules:
    - host: {{ .Values.domainLegacy }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-ads-console
                port:
                  name: https-console
