apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ads-cert
spec:
  secretName: minio-ads-cert
  dnsNames:
    - {{ .Values.domain }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-ads-cert-legacy
spec:
  secretName: minio-ads-cert-legacy
  dnsNames:
    - {{ .Values.domainLegacy }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
