apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-ads-secret-env
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: minio-ads-secret-env       # name of the k8s Secret to be created
  data:
  - secretKey: config.env
    remoteRef:
      key: minio-ads-secret-env
      property: config.env
