{{- with .Values.cluster }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .name }}
spec:
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    logging: debug
    enableSaramaLogging: true
  kafka:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    version: 3.6.0
    replicas: {{ .kafka.replicas }}
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
        #networkPolicyPeers:
        #- namespaceSelector: {}
        #  podSelector:
        #    matchLabels:
        #      app.kubernetes.io/name: kafka-ui
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .kafka.diskSize }}
        deleteClaim: true
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    replicas: {{ .zooKeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .zooKeeper.diskSize }}
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}