apiVersion: batch/v1
kind: CronJob
metadata:
  name: kibana-backup
spec:
  schedule: "0 */4 * * *" # Every 4 hours
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          containers:
          - name: gcloud-ubuntu
            image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - /scripts/job.bash
            env:
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: es-ads-basic-authen
                  key: username
            - name: GOOGLE_APPLICATION_CREDENTIALS 
              value: /secrets/gcp-sa.json
            - name: BUCKET_NAME
              value: rtarf-backup
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-ads-basic-authen
                  key: password
            - name: SLACK_URI
              valueFrom:
                secretKeyRef:
                  name: cron-secret
                  key: slack-uri

            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: secrets
              readOnly: true
              mountPath: "/secrets"

          restartPolicy: OnFailure

          volumes:
          - name: scripts
            configMap:
              name: script-cm
          - name: secrets
            secret:
              secretName: gcp-sa
