apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cron-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: cron-secret       # name of the k8s Secret to be created
  data:
  - secretKey: slack-uri
    remoteRef:
      key: initial-secret
      property: SLACK_URI
