apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-ads-basic-authen-legacy
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: es-ads-basic-authen-legacy       # name of the k8s Secret to be created
  data:
  - secretKey: username
    remoteRef:
      key: initial-secret
      property: ES_USER2

  - secretKey: password
    remoteRef:
      key: initial-secret
      property: ES_PASSWORD2

  - secretKey: roles
    remoteRef:
      key: initial-secret
      property: ES_ROLE2
