apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-soc-cert-legacy
spec:
  secretName: kibana-soc-cert-legacy
  dnsNames:
    - {{ .Values.domain2 }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
