apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-soc-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: kibana-soc-cert
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: es-ads-kb-http
                port:
                  number: 5601
