apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: thehive
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'thehive-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-rke2-labs-addons.git
        targetRevision: "{{name}}" #Based on environment
        path: '03-argocd-apps/manifests/thehive'
      destination:
        name: in-cluster
        namespace: thehive
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
