apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: es-training
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'es-training-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/rtaf-soc/rtarf-rke2-labs-addons.git
        targetRevision: "{{name}}" #Based on environment
        path: '03-argocd-apps/manifests/es-training'
      destination:
        name: in-cluster
        namespace: es-training
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
