apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-k8s-ing-legacy
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainLegacy }}
      secretName: grafana-k8s-cert-legacy
  rules:
    - host: {{ .Values.domainLegacy }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-{{ .Values.environment }}-grafana
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ing-legacy
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domain2Legacy }}
      secretName: grafana-k8s-cert-legacy
  rules:
    - host: {{ .Values.domain2Legacy }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-prometheus
                port:
                  number: 9090
