apiVersion: v1
kind: Service
metadata:
  labels:
    app: thehive
  name: thehive
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: http
  selector:
    app: thehive
