domain: grafana-log.rtarf-labs.its-software-services.com

loki-stack:
  grafana:
    grafana.ini:
      server:
        root_url: https://grafana-log.rtarf-labs.its-software-services.com
        domain: grafana-log.rtarf-labs.its-software-services.com
