cert-manager:
  enabled: true
  global:
    leaderElection:
      namespace: cert-manager

  installCRDs: true
  fullnameOverride: cert-manager
  extraArgs:
    - --dns01-recursive-nameservers-only=true
    - --dns01-recursive-nameservers=172.21.2.101:53 # RTARF Internal DNS
